# Generated by Django 5.1.6 on 2025-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_donation_donationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='deliverypic',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
