# Generated by Django 5.2 on 2025-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationarea',
            name='description',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation'), ('Blood Donation', 'Blood Donation'), ('Books Donation', 'Books Donation'), ('Furniture Donation', 'Furniture Donation'), ('Vessel Donation', 'Vessel Donation'), ('Organ Donation', 'Organ Donation'), ('Art Donation', 'Art Donation'), ('Cash Donation', 'Cash Donation'), ('Medical Donation', 'Medical Donation'), ('Legacy Donation', 'Legacy Donation'), ('Plant Donation', 'Plant Donation')], max_length=100, null=True),
        ),
    ]
